/** Pool to draw 10 random preset avatars per profile visit (Dicebear seeds). */
export const AVATAR_SEED_POOL: string[] = [
  'Felix',
  'Aneka',
  'Milo',
  'Zoe',
  'Kai',
  'Nova',
  'Leo',
  'Ivy',
  'Theo',
  'Ruby',
  'Oliver',
  'Luna',
  'Finn',
  'Aria',
  'Jasper',
  'Willow',
  'Oscar',
  'Sage',
  'River',
  'Sky',
  'Blaze',
  'Cleo',
  'Duke',
  'Echo',
  'Flora',
  'Gizmo',
  'Hazel',
  'Indigo',
  'Juno',
  'Koda',
  'Loki',
  'Mochi',
  'Nimbus',
  'Orion',
  'Pixel',
  'Quinn',
  'Remy',
  'Storm',
  'Toby',
  'Vega',
]

export function dicebearUrl(seed: string): string {
  return `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(seed)}`
}
